/*
 * This source file was generated by the Gradle 'init' task
 */
package o2.dip;

public class App {
    public static void main(String[] args) {
        var dipClient = new DipClient(new String[]{"dip/acc/*"});
    }
}
