[versions]
log4j = "2.23.1"

[libraries]
log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4jApi = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
